os: osx
language: ruby
rvm: 2.5.0
sudo: false
cache: bundler

branches:
  only:
  - master

notifications:
  email:
    recipients:
    - $EMAIL
    on_success: always
    on_failure: always

env:
  global:
  - JEKYLL_ENV=production
  - DEPLOY_KEY=deploy_rsa
  - LOCAL_PATH=_site
  - JEKYLL_CONF=_config.yml

addons:
  homebrew:
    packages:
    - rsync

before_install:
  - gem update --system
  - gem update bundler

install:
  - bundle install

script:
  - bundle exec jekyll build --config $JEKYLL_CONF

before_deploy:
- ssh-keyscan -t rsa -H $HOST >> $HOME/.ssh/known_hosts
- openssl aes-256-cbc -K $encrypted_57051782bb65_key -iv $encrypted_57051782bb65_iv -in $DEPLOY_KEY.enc -out /tmp/$DEPLOY_KEY -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/$DEPLOY_KEY
- ssh-add /tmp/$DEPLOY_KEY

deploy:
  provider: script
  skip_cleanup: true
  script: rsync --recursive --relative --delete-after --progress --stats $LOCAL_PATH $USERNAME@$HOST:$REMOTE_PATH

after_deploy:
- ssh-add -D /tmp/$DEPLOY_KEY
- rm /tmp/$DEPLOY_KEY