dist: xenial
language: ruby

install:
  - bundle install
  - gem install jekyll

branches:
  only:
    - feature/scripts

env:
  global:
    - JEKYLL_ENV=production

notifications:
  email:
    recipients:
      - gael.foppolo@gmail.com
    on_success: always
    on_failure: always

script:
  - chmod +x journal.sh
  - bash journal.sh --build || travis_terminate 1;

after_success:
  - chmod +x journal.sh
  - bash journal.sh --publish || travis_terminate 1;

sudo: false
addons:
  apt:
    packages:
      - lftp