# Site
title: /var/log/journal
description: >-
  Thoughts, stories and ideas.
url: https://www.gaelfoppolo.com
timezone: Europe/Paris
lang: en-US
permalink: /:title/

# Author
author:
  name: Gaël Foppolo
  email: me@gaelfoppolo.com

# Build
markdown: kramdown
highlighter: rouge
date_format: "%d<sup>%o</sup> %B %Y"

# Front matter defaults 
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      share: true
      paginate: false
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "meta"
    values:
      layout: "page"

# Collections
collections:
  meta:
    output: true
    permalink: /:path/
  pages:
    output: true
    permalink: /:path/

# Setup
include: [".well-known"]
exclude: ["README*", "LICENSE*", "Gemfile*", "journal.sh", ".travis.yml"]

# Pagination
paginate_path: "/history/:num/"
pagination:
  enabled: true
  per_page: 5
  permalink: '/history/:num/'
  sort_field: 'date'
  sort_reverse: true

# Archives
jekyll-archives:
  enabled: 
    - categories
  layouts:
    category: 'category'
  permalinks:
    category: '/category/:name/'

# Assets Pipeline
assets:
  sources:
    - _assets
    - _assets/images
    - _assets/js
    - _assets/css
    - _assets/fonts

# Analytics
analytics:
  url: analytics.gaelfoppolo.com
  siteId: "1"